id = "alter_headers"
type = "snippet"
name = "Alter Headers"
description = "Change the headers sent in a request or returned in a response"
demo_url = "https://cloudflareworkers.com/#5386d315ec8c899370e8e5d00cf88939:https://tutorial.cloudflareworkers.com"
share = "/templates/snippets/alter_headers"
