id = "binast_cf_worker"
type ="featured_boilerplate"
title = "Binast-Cf-Worker"
description = "Serve BinAST via a Cloudflare Worker"
repository_url = "https://github.com/xtuc/binast-cf-worker-template"
demo_url = "https://serve-binjs.that-test.site/"

tags = ['Middleware']