id="bulk_origin_proxies"
type ="snippet"
title = "Bulk Origin Proxies"
description = "Resolve requests to your domain to a set of proxy third-party origins"
code = """
async function handleRequest(request) {
  let url = new URL(request.url)
  // Check if incoming hostname is
  // a key in the ORIGINS object
  let target = ORIGINS[url.hostname]
  // If it is, proxy request to that third party origin
  if (target) {
    url.hostname = target
    return fetch(url, request)
  }
  // Otherwise, process request as normal
  return fetch(request)
}
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})
/**
 * An object with different url's to fetch
 * @param {Object} ORIGINS
 */
const ORIGINS = {
  'starwarsapi.yourdomain.com': 'swapi.co',
  'google.yourdomain.com': 'google.com',
}
"""

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/#545c79e098708ca658dcbdb860c5021a:https://starwarsapi.yourdomain.com/"
share_url = "/templates/snippets/bulk_origin_proxies"