id = "img_color_worker"
type ="featured_boilerplate"
title = "Img-Color-Worker"
description = "Retrieve the dominant color of a PNG or JPEG image"
repository_url = "https://github.com/xtuc/img-color-worker"

tags = ['Middleware']