type ="featured_boilerplate"
title = "Sentry"
description = "Log exceptions and errors in your Workers application to Sentry.io -  an error tracking tool"
id = "sentry"
repository_url = "https://github.com/bustle/cf-sentry"
tags = ['Middleware']