id = "sites"
type ="featured_boilerplate"
title = "Worker Sites"
description = "Get started with Workers Sites to easily deploy static assets to the Cloudflare edge."
repository_url = "--site"
tags = ['Originless']
tutorial = "/sites/start-from-scratch"