id = "alter_headers"
weight = 1
type = "snippet"
title = "Alter Headers"
description = "Change the headers sent in a request or returned in a response"

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/#5386d315ec8c899370e8e5d00cf88939:https://tutorial.cloudflareworkers.com"
share_url = "/templates/snippets/alter_headers"
