id = "block_on_tls_version"
weight = 1
type = "snippet"
title = "Block on TLS Version"
description = "Inspects the incoming request's TLS version and blocks if under TLSv1.2."
tags = [ "Middleware" ]
