id = "emscripten"
weight = 1
type ="featured_boilerplate"
title = "Emscripten + Wasm Image Resizer"
description = "Image Resizer in C compiled to Wasm with Emscripten"
repository_url = "https://github.com/cloudflare/worker-emscripten-template"

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/#ddb7fa39e09cdf734180c5d083ddb390:http://placehold.jp/1200x800.png"

tags = ['Wasm']