id = "hotlink_protection"
weight = 1
type = "snippet"
title = "Hot-link Protection"
description = "Block other websites from linking to your content"

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/#d659b20dcf91df6e6de1bedbb94f6702:https://www.cloudflare.com/img/logo-cloudflare-dark.svg"
share_url = "/templates/snippets/hotlink-protection"
