id = "router"
type = "boilerplate"
title = "Router"
description = "Selects the logic based on the `request` method and URL. Use with REST APIs or apps that require routing logic."
repository_url = "https://github.com/cloudflare/worker-template-router"
url = "/templates/boilerplates/router"
weight = 97

share_url = "/templates/boilerplates/router"

[demos.bar]
text = "Demo /bar"
url = "https://cloudflareworkers.com/#6cbbd3ae7d4e928da3502cb9ce11227a:https://tutorial.cloudflareworkers.com/bar"

[demos.foo]
text = "Demo /foo"
url = "https://cloudflareworkers.com/#6cbbd3ae7d4e928da3502cb9ce11227a:https://tutorial.cloudflareworkers.com/foo"
