id = "signed_request"
weight = 10
type = "snippet"
title = "Signed Request/Response"
description = "Check signatures of requests and sign responses with a private key"
share_url = "/templates/snippets/signed_request"

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/?hide_editor#c22ea0102fb9dced927a9b870e9c546a:https://example.com/"
