id = "sites"
weight = 1
type = "featured_boilerplate"
title = "Worker Sites"
description = "Get started with Workers Sites to easily deploy static assets to the Cloudflare edge."
repository_url = "https://github.com/cloudflare/worker-sites-template"
tags = [ "Originless" ]

share_url = "/sites/start-from-scratch"
